# Isaac Sim / RoArm M3 도메인 랜덤라이제이션 기본값 예시
physics:
  dt_jitter: [0.0, 0.0005]
  solver_position_iteration_range: [4, 8]
  solver_velocity_iteration_range: [1, 2]

robot:
  joint_friction_scale: [0.8, 1.2]
  motor_strength_scale: [0.9, 1.1]
  link_mass_scale: [0.95, 1.05]

sensors:
  camera_extrinsic_noise: 0.002  # rad
  camera_intrinsic_focal_rand: [0.99, 1.01]
  depth_scale_noise: 0.01

environment:
  table_friction_scale: [0.7, 1.3]
  light_intensity_scale: [0.8, 1.2]
  texture_randomization: true

curriculum:
  phase_thresholds:
    - { phase: 0, success_rate: 0.0, difficulty: easy }
    - { phase: 1, success_rate: 0.6, difficulty: medium }
    - { phase: 2, success_rate: 0.8, difficulty: hard }
